export const heroes = [
  { abbr: "a", name: "Accursed" },
  { abbr: "aluna", name: "Aluna" },
  { abbr: "andro", name: "Andromeda" },
  { abbr: "ara", name: "Arachna" },
  { abbr: "arma", name: "Armadon" },
  { abbr: "art", name: "Artesia" },
  { abbr: "arti", name: "Artillery" },
  { abbr: "balph", name: "Balphagore" },
  { abbr: "behe", name: "Behemoth" },
  { abbr: "bs", name: "Blacksmith" },
  { abbr: "blitz", name: "Blitz" },
  { abbr: "bh", name: "Blood Hunter" },
  { abbr: "bomb", name: "Bombardier" },
  { abbr: "bramb", name: "Bramble" },
  { abbr: "bubbs", name: "Bubbles" },
  { abbr: "bush", name: "Bushwack" },
  { abbr: "c", name: "Chronos" },
  { abbr: "cd", name: "Corrupted Disciple" },
  { abbr: "damp", name: "Dampeer" },
  { abbr: "dw", name: "Deadwood" },
  { abbr: "de", name: "Defiler" },
  { abbr: "ds", name: "Demented Shaman" },
  { abbr: "devo", name: "Devourer" },
  { abbr: "dr", name: "Doctor Repulsor" },
  { abbr: "drac", name: "Draconis" },
  { abbr: "dm", name: "Drunken Master" },
  { abbr: "elec", name: "Electrician" },
  { abbr: "ew", name: "Emerald Warden" },
  { abbr: "emp", name: "Empath" },
  { abbr: "engi", name: "Engineer" },
  { abbr: "f", name: "Fayde" },
  { abbr: "flint", name: "Flint Beastwood" },
  { abbr: "flux", name: "Flux" },
  { abbr: "fa", name: "Forsaken Archer" },
  { abbr: "gaunt", name: "Gauntlet" },
  { abbr: "gemi", name: "Gemini" },
  { abbr: "geo", name: "Geomancer" },
  { abbr: "glac", name: "Glacius" },
  { abbr: "gk", name: "Gravekeeper" },
  { abbr: "grin", name: "Grinex" },
  { abbr: "hs", name: "Hammerstorm" },
  { abbr: "hb", name: "Hellbringer" },
  { abbr: "jere", name: "Jereziah" },
  { abbr: "kotf", name: "Keeper of the forest" },
  { abbr: "k", name: "Kinesis" },
  { abbr: "krak", name: "Kraken" },
  { abbr: "legio", name: "Legionnaire" },
  { abbr: "lode", name: "Lodestone" },
  { abbr: "ls", name: "Lord Salforis" },
  { abbr: "mm", name: "Madman" },
  { abbr: "mb", name: "Magebane" },
  { abbr: "mag", name: "Magmus" },
  { abbr: "mali", name: "Maliken" },
  { abbr: "mart", name: "Martyr" },
  { abbr: "moa", name: "Master of Arms" },
  { abbr: "mon", name: "Monarch" },
  { abbr: "mq", name: "Moon Queen" },
  { abbr: "morax", name: "Moraxus" },
  { abbr: "myrm", name: "Myrmidon" },
  { abbr: "nh", name: "Night Hound" },
  { abbr: "nymph", name: "Nymphora" },
  { abbr: "oogie", name: "Oogie" },
  { abbr: "oph", name: "Ophelia" },
  { abbr: "panda", name: "Pandamonium" },
  { abbr: "para", name: "Parasite" },
  { abbr: "pearl", name: "Pearl" },
  { abbr: "pebbs", name: "Pebbles" },
  { abbr: "pesti", name: "Pestilence" },
  { abbr: "phara", name: "Pharao" },
  { abbr: "pr", name: "Plague Rider" },
  { abbr: "polly", name: "Pollywog Priest" },
  { abbr: "pred", name: "Predator" },
  { abbr: "pris", name: "Prisoner 945" },
  { abbr: "pm", name: "Puppet Master" },
  { abbr: "pyro", name: "Pyromancer" },
  { abbr: "rally", name: "Rally" },
  { abbr: "ramp", name: "Rampage" },
  { abbr: "reve", name: "Revenant" },
  { abbr: "rhaps", name: "Rhapsody" },
  { abbr: "rift", name: "Riftwalker" },
  { abbr: "sw", name: "Sand Wraith" },
  { abbr: "scout", name: "Scout" },
  { abbr: "sb", name: "Shadowblade" },
  { abbr: "benz", name: "Sir Benzington" },
  { abbr: "s", name: "Slither" },
  { abbr: "sol", name: "Solstice" },
  { abbr: "sr", name: "Soul Reaper" },
  { abbr: "ss", name: "Soulstealer" },
  { abbr: "succu", name: "Succubus" },
  { abbr: "swift", name: "Swiftblade" },
  { abbr: "temp", name: "Tempest" },
  { abbr: "chip", name: "The Chipper" },
  { abbr: "tdl", name: "The Dark Lady" },
  { abbr: "tb", name: "Thunderbringer" },
  { abbr: "tort", name: "Torturer" },
  { abbr: "tr", name: "Tremble" },
  { abbr: "t", name: "Tundra" },
  { abbr: "valk", name: "Valkyrie" },
  { abbr: "vindi", name: "Vindicator" },
  { abbr: "vj", name: "Voodoo Jester" },
  { abbr: "wb", name: "War Beast" },
  { abbr: "w", name: "Wildsoul" },
  { abbr: "ws", name: "Witch Slayer" },
  { abbr: "wh", name: "Wretched Hag" },
  { abbr: "z", name: "Zephyr" },
];
